import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  trailingSlash: true,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "cms.sweetleaves.co" },
    ],
  },
  async redirects() {
    const base = process.env.NEXT_PUBLIC_SITE_URL ?? "https://sweetleaves.co";
    return [
      { source: "/in-store-shopping/", destination: `${base}/`, permanent: true },
      { source: "/press/", destination: `${base}/blog/`, permanent: true },
      { source: "/author/sweetleavesadmin/", destination: `${base}/`, permanent: true },
      { source: "/cannabis-101/", destination: `${base}/blog/`, permanent: true },
      { source: "/cannabis-seeds/", destination: `${base}/shop-recreational-cannabis/`, permanent: true },
      { source: "/cbd/", destination: `${base}/shop-recreational-cannabis/`, permanent: true },
      { source: "/edina-mn/", destination: `${base}/`, permanent: true },
      { source: "/higher-education/", destination: `${base}/blog/`, permanent: true },
      { source: "/higher-love/", destination: `${base}/blog/`, permanent: true },
      { source: "/location/minneapolis/", destination: `${base}/`, permanent: false },
      { source: "/minh-le-studio/", destination: `${base}/shop-recreational-cannabis/`, permanent: true },
      { source: "/minneapolis-mn/", destination: `${base}/`, permanent: false },
      { source: "/minnetonka-mn/", destination: `${base}/`, permanent: false },
      { source: "/premium-cannabis-dispensary-edina-mn/", destination: `${base}/`, permanent: true },
      { source: "/premium-cannabis-dispensary-minneapolis-mn/", destination: `${base}/`, permanent: false },
      { source: "/premium-cannabis-dispensary-minnetonka-mn/", destination: `${base}/`, permanent: false },
      { source: "/premium-cannabis-dispensary-st-louis-park-mn/", destination: `${base}/`, permanent: true },
      { source: "/premium-cannabis-dispensary-st-paul-mn/", destination: `${base}/`, permanent: true },
      { source: "/recreational-cannabis/", destination: `${base}/shop-recreational-cannabis/`, permanent: true },
      { source: "/richfield-mn/", destination: `${base}/`, permanent: true },
      { source: "/session-goods/", destination: `${base}/shop-recreational-cannabis/`, permanent: true },
      { source: "/st-louis-park-mn/", destination: `${base}/`, permanent: true },
      { source: "/st-paul-mn/", destination: `${base}/`, permanent: true },
      { source: "/birchs-on-the-lake/", destination: `${base}/brands/birchs-on-the-lake/`, permanent: true },
      { source: "/blncd/", destination: `${base}/`, permanent: true },
      { source: "/cann/", destination: `${base}/`, permanent: true },
      { source: "/clrty/", destination: `${base}/`, permanent: true },
      { source: "/dogwalkers/", destination: `${base}/brands/dogwalkers/`, permanent: true },
      { source: "/find-wunder/", destination: `${base}/`, permanent: true },
      { source: "/gigli/", destination: `${base}/brands/gigli/`, permanent: true },
      { source: "/good-green/", destination: `${base}/brands/good-green/`, permanent: true },
      { source: "/grasslandz/", destination: `${base}/brands/grasslandz/`, permanent: true },
      { source: "/lakeside-cannabis-co/", destination: `${base}/brands/lakeside-cannabis-co/`, permanent: true },
      { source: "/mary-jane/", destination: `${base}/brands/mary-jane/`, permanent: true },
      { source: "/nebula/", destination: `${base}/brands/nebula/`, permanent: true },
      { source: "/nowadays/", destination: `${base}/brands/nowadays/`, permanent: true },
      { source: "/oliphant-brewing/", destination: `${base}/brands/oliphant-brewing/`, permanent: true },
      { source: "/ongrok/", destination: `${base}/`, permanent: true },
      { source: "/raw/", destination: `${base}/`, permanent: true },
      { source: "/rythm/", destination: `${base}/brands/rythm/`, permanent: true },
      { source: "/studio-tbd/", destination: `${base}/`, permanent: true },
      { source: "/sweetleaves/", destination: `${base}/brands/sweetleaves/`, permanent: true },
      { source: "/wild-state-cider-birdie/", destination: `${base}/brands/wild-state-cider-birdie/`, permanent: true },
      { source: "/wyld/", destination: `${base}/brands/wyld/`, permanent: true },
      { source: "/cannabis-accessories/", destination: `${base}/`, permanent: true },
      { source: "/cannabis-beverages/", destination: `${base}/products/cannabis-beverages/`, permanent: true },
      { source: "/disposable-vapes-and-carts/", destination: `${base}/products/disposable-vapes-and-carts/`, permanent: true },
      { source: "/edibles/", destination: `${base}/products/edibles/`, permanent: true },
      { source: "/flower/", destination: `${base}/products/flower/`, permanent: true },
      { source: "/pre-rolls/", destination: `${base}/products/pre-rolls/`, permanent: true },
      { source: "/faq/", destination: `${base}/faqs/`, permanent: true },
      { source: "/shop/", destination: `${base}/shop-recreational-cannabis/`, permanent: true },
      { source: "/learn/", destination: `${base}/blog/`, permanent: true },
      { source: "/learn/:path*/", destination: `${base}/blog/:path*/`, permanent: true },
      { source: "/careers/", destination: `${base}/contact/`, permanent: true },
      { source: "/quick-links/", destination: `${base}/`, permanent: true },
      { source: "/shop-now/", destination: `${base}/shop-recreational-cannabis/`, permanent: true},
    ];
  },
};

export default nextConfig;
